default_config:

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# -----------

sensor:
  - platform: hass_wakatime
    api_url: !secret wakatime_api_url
    api_key: !secret wakatime_api_key
    user: !secret wakatime_user

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

logger:
  default: info
  logs:
    custom_components.hass_wakatime: debug
